name: 'Create Release'

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git to use our bot token
        uses: de-vri-es/setup-git-credentials@v2.0.10
        with:
          credentials: "https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com"
      - name: Checkout git ref
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create artifact
        id: artifact
        run: |
          mkdir release
          _artifact_file="$(pwd)/release/deploy-image-action-${{ github.ref_name }}.tar.gz"
          tar \
            -zcvf "${_artifact_file}" \
            --exclude '.git' \
            --exclude '.github' \
            --exclude '.gitignore' \
            --exclude 'release' \
            .
          echo "artifact_filepath=${_artifact_file}" >> $GITHUB_OUTPUT
      - name: Create GitHub release
        uses: ncipollo/release-action@v1.16.0
        with:
          artifacts: '${{ steps.artifact.outputs.artifact_filepath }}'
          generateReleaseNotes: "true"
          artifactErrorsFailBuild: "true"
          allowUpdates: "true"
          omitBodyDuringUpdate: "true"
          omitNameDuringUpdate: "true"
          replacesArtifacts: "true"
          token: '${{ secrets.GITHUB_TOKEN }}'
